php:

  risky: false

  version: 8.4

  presets: recommended

  finder:
    exclude:
      - "tests"
      - "docs"
      - "log"
    name: "*.php"
    not-name:
      - "*Stub.php"
      - "*.blade.php"
    contains:
      - "Foo"
    not-contains:
      - "config"
    path:
      - "foo/Stuff"
    not-path:
      - "libraries"
    depth:
      - "< 2"
